- id: wosuid:WOS:000609182100023
  remove: true

- id: doi:10.1016/J.JHAZMAT.2025.137562
  #image: "/shahlab/images/highlights_picture2.jpg"
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0304389425004765-ga1.jpg

- id: doi:10.1016/J.BUILDENV.2024.112221
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0360132324010631-gr2.jpg

- id: doi:10.1002/AWS2.1382
  image: "shahlab/images/publications_isaacson_awwa_paper.jpg"

- id: doi:10.1016/J.BUILDENV.2023.110953
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0360132323009800-gr1.jpg
  
- id: doi:10.1371/JOURNAL.PWAT.0000141
  image: https://journals.plos.org/water/article/figure/image?size=medium&id=10.1371/journal.pwat.0000141.g001

- id: doi:10.1016/j.envadv.2023.100386
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2666765723000467-gr1.jpg

- id: doi:10.1021/ACS.EST.3C00700
  image: https://pubs.acs.org/cms/10.1021/acs.est.3c00700/asset/images/medium/es3c00700_0007.gif

- id: doi:10.1093/ANNWEH/WXAC096
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/annweh/67/4/10.1093_annweh_wxac096/1/m_wxac096f0001.jpeg?Expires=1784248718&Signature=xahzTC56YiFW91p3SK6-IvD-8Bl8n4qPQn1Yuy4KfURXSvZOr3Hp1fjlBUNCUitYTLTQW4n5ApphXRfZPjMU3g8zfu2NCAmDHzegzU8u6vq~b-Fg~Abau37pw4tYjdImswmvOlKlocrCcrorCdWx24UGj4Es4InBl1Ci4boqC3OvHIB9t~z0f8av4dX2mHEh0OIHnmgZK~8vCbYEQtk9zh4WZA-tb0YeJuRlQ~jcjYunX37hxqp4Nlf2yqmQntOTuLHwugfhgf4VuxDNuWbnY7GeVN65yT9pTYsI48uAh4rpYXCvR-ax5kQwiBraq-pinjHl3pE-6ZNF5MC7gk2BzQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1002/WER.1650
  image: https://onlinelibrary.wiley.com/cms/asset/b26e4410-5388-4ecb-a865-1a349135a84c/wer1650-toc-0001-m.png

- id: doi:10.1016/J.HAZL.2021.100042
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2666911021000307-ga1.jpg
  
- id: doi:10.1016/J.MEMSCI.2021.119717
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0376738821006633-ga1.jpg
  
- id: doi:10.1021/ACS.ESTLETT.1C00390
  image: https://pubs.acs.org/cms/10.1021/acs.estlett.1c00390/asset/images/medium/ez1c00390_0003.gif

- id: doi:10.1007/S11069-021-04714-9
  image: https://media.springernature.com/m312/springer-static/image/art%3A10.1007%2Fs11069-021-04714-9/MediaObjects/11069_2021_4714_Fig1_HTML.png?

- id: doi:10.1021/ACS.EST.0C06122
  image: https://pubs.acs.org/cms/10.1021/acs.est.0c06122/asset/images/medium/es0c06122_0010.gif

- id: doi:10.1039/D0EW00836B
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=D0EW00836B&imageInfo.ImageIdentifier.Year=2021

- id: doi:10.1002/AWS2.1183
  image: https://awwa.onlinelibrary.wiley.com/cms/asset/d3da99fc-bd61-4fca-a346-df0d688c893a/aws21183-fig-0001-m.jpg
  
- id: doi:10.1039/D0EM00219D
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=D0EM00219D&imageInfo.ImageIdentifier.Year=2020

- id: doi:10.1039/D0EW00262C
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=D0EW00262C&imageInfo.ImageIdentifier.Year=2020
  
- id: doi:10.1016/J.BUILDENV.2019.106566
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0360132319307784-fx1.jpg

- id: doi:10.1021/ACS.ESTLETT.9B00397
  image: https://pubs.acs.org/cms/10.1021/acs.estlett.9b00397/asset/images/medium/ez9b00397_0004.gif

- id: doi:10.1021/ACS.EST.9B01446
  image: https://pubs.acs.org/cms/10.1021/acs.est.9b01446/asset/images/medium/es-2019-014462_0008.gif

- id: doi:10.1039/C7EW00439G
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=C7EW00439G&imageInfo.ImageIdentifier.Year=2018

- id: doi:10.1016/J.WATRES.2018.06.042
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0043135418304925-fx1.jpg
  
- id: doi:10.1021/ACS.EST.8B01618
  image: https://pubs.acs.org/cms/10.1021/acs.est.8b01618/asset/images/medium/es-2018-01618s_0002.gif

- id: doi:10.1021/ES503920N
  image: https://pubs.acs.org/cms/10.1021/es503920n/asset/images/medium/es-2014-03920n_0007.gif

- id: doi:10.1039/C5EW00061K
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=C5EW00061K&imageInfo.ImageIdentifier.Year=2015

- id: doi:10.1016/J.CHEMOSPHERE.2014.03.135
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0045653514005268-gr1.jpg

- id: doi:10.1021/ES304893M
  image: https://pubs.acs.org/cms/10.1021/es304893m/asset/images/medium/es-2012-04893m_0005.gif

- id: doi:10.1021/ES301867B
  image: https://pubs.acs.org/cms/10.1021/es301867b/asset/images/medium/es-2012-01867b_0006.gif

- id: doi:10.1021/ES204717J
  image: https://pubs.acs.org/cms/10.1021/es204717j/asset/images/medium/es-2011-04717j_0001.gif

- id: doi:10.1021/ES203312S
  image: https://pubs.acs.org/cms/10.1021/es203312s/asset/images/medium/es-2011-03312s_0007.gif

- id: doi:10.1016/J.MEMSCI.2011.10.034
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0376738811007940-gr2.sml

- id: doi:10.1016/J.WATRES.2011.09.010
  image: https://ars.els-cdn.com/content/image/1-s2.0-S004313541100529X-fx1.jpg

- id: doi:10.1021/ES104240V
  image: https://pubs.acs.org/cms/10.1021/es104240v/asset/images/medium/es-2010-04240v_0005.gif

- id: doi:10.1021/ES060404C
  image: https://pubs.acs.org/cms/10.1021/es060404c/asset/images/medium/es060404cf00001.gif

- id: doi:10.1021/ES050054E
  image: https://pubs.acs.org/cms/10.1021/es050054e/asset/images/medium/es050054ef00001.gif

- id: doi:10.1016/S0006-3495(02)75579-3
  image: https://www.cell.com/cms/10.1016/S0006-3495(02)75579-3/asset/6dd4fb90-879d-4a11-9b00-202c3c4b619a/main.assets/gr1.jpg

- id: doi:10.2307/3393148
  image: https://www.jstor.org/cover-image/7bc77995-6d68-3618-8744-a9c79145ef9f

# comment out information below

#- id: doi:10.1371/journal.pcbi.1007128
  #type: paper
  #description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  #date: 2020-12-4
  #image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  #buttons:
   # - type: manubot
   #   link: https://greenelab.github.io/meta-review/
   # - type: source
   #   text: Manuscript Source
   #   link: https://github.com/greenelab/meta-review
   # - type: website
   #   link: http://manubot.org/
  #tags:
   # - open science
   # - collaboration
  #repo: greenelab/meta-review

# - id: doi:10.1016/j.csbj.2020.05.017
#  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

#- id: doi:10.7554/eLife.32822
#  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp


